import jsPDF from 'jspdf';
import { GameSession } from './types';
import { formatCurrency, formatChips } from './calculations';

export function generateSessionPDF(
  session: GameSession, 
  getPlayerName: (id: string) => string
): jsPDF {
  const doc = new jsPDF();
  const { settings, results, settlements, totals } = session;
  
  // Colors
  const primaryColor: [number, number, number] = [34, 197, 94]; // Green
  const textColor: [number, number, number] = [30, 30, 30];
  const mutedColor: [number, number, number] = [100, 100, 100];
  
  let y = 20;
  
  // Title
  doc.setFontSize(24);
  doc.setTextColor(...primaryColor);
  doc.text('PokerSplit', 105, y, { align: 'center' });
  y += 10;
  
  // Subtitle
  doc.setFontSize(14);
  doc.setTextColor(...mutedColor);
  doc.text('Session Report', 105, y, { align: 'center' });
  y += 15;
  
  // Session info
  doc.setFontSize(12);
  doc.setTextColor(...textColor);
  doc.text(`Title: ${session.title}`, 20, y);
  y += 8;
  
  doc.text(`Date: ${new Date(session.createdAt).toLocaleDateString()}`, 20, y);
  y += 8;
  
  const modeText = settings.mode === 'money' ? 'Money Mode' : 'Points Mode';
  doc.text(`Mode: ${modeText}`, 20, y);
  y += 8;
  
  doc.text(`Buy-in: ${formatCurrency(settings.buyInValue, settings.currencySymbol)} (${formatChips(settings.chipsPerBuyIn)} chips)`, 20, y);
  y += 8;
  
  doc.text(`Total Pot: ${formatCurrency(totals.totalMoney, settings.currencySymbol)}`, 20, y);
  y += 15;
  
  // Divider
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 10;
  
  // Results table header
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.text('Results', 20, y);
  y += 10;
  
  // Table headers
  doc.setFontSize(10);
  doc.setTextColor(...mutedColor);
  doc.text('Player', 20, y);
  doc.text('Buy-ins', 70, y);
  doc.text('Chips', 95, y);
  doc.text('Invested', 125, y);
  doc.text('Cash Out', 155, y);
  doc.text('Net', 180, y);
  y += 6;
  
  // Table rows
  doc.setTextColor(...textColor);
  const sortedResults = [...results].sort((a, b) => b.netAmount - a.netAmount);
  
  for (const result of sortedResults) {
    const playerName = getPlayerName(result.playerId);
    doc.text(playerName.substring(0, 12), 20, y);
    doc.text(result.buyIns.toString(), 70, y);
    doc.text(formatChips(result.chips), 95, y);
    doc.text(formatCurrency(result.invested, settings.currencySymbol), 125, y);
    doc.text(formatCurrency(result.cashOut, settings.currencySymbol), 155, y);
    
    // Color net amount
    if (result.netAmount > 0) {
      doc.setTextColor(34, 197, 94);
    } else if (result.netAmount < 0) {
      doc.setTextColor(239, 68, 68);
    }
    const sign = result.netAmount > 0 ? '+' : '';
    doc.text(`${sign}${formatCurrency(result.netAmount, settings.currencySymbol)}`, 180, y);
    doc.setTextColor(...textColor);
    
    y += 6;
  }
  
  y += 10;
  
  // Settlements
  if (settlements.length > 0) {
    doc.setDrawColor(...primaryColor);
    doc.line(20, y, 190, y);
    y += 10;
    
    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    doc.text('Settlements', 20, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(...textColor);
    
    for (const s of settlements) {
      const status = s.settled ? '✓ PAID' : 'Pending';
      const fromName = getPlayerName(s.fromPlayerId);
      const toName = getPlayerName(s.toPlayerId);
      doc.text(`${fromName} → ${toName}: ${formatCurrency(s.amount, settings.currencySymbol)} [${status}]`, 20, y);
      y += 6;
    }
  }
  
  // Footer
  y = 280;
  doc.setFontSize(8);
  doc.setTextColor(...mutedColor);
  doc.text('Generated by PokerSplit', 105, y, { align: 'center' });
  
  return doc;
}

export function downloadSessionPDF(
  session: GameSession, 
  getPlayerName: (id: string) => string
): void {
  const doc = generateSessionPDF(session, getPlayerName);
  const filename = `pokersplit-${session.title.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
